java_test(
    name = "GreetingTest",
    srcs = ["GreetingTest.java"],
    test_class = "src.test.java.com.example.cmdline.GreetingTest",
    deps = [
        "//src/main/java/com/example/cmdline",
        "//src/main/java/com/example:greeter"
    ],
)